// De prompt achter de knop 'AI-prompt kopiëren' in het adminscherm.
//
// De twee lijsten met categorieën en leeftijden worden uit data.js gehaald in
// plaats van hier uitgeschreven. Anders raakt de prompt achterop zodra er een
// label bijkomt of samengevoegd wordt, en krijg je tekst aangeleverd met een
// categorie die niet meer bestaat.
function bouwAiPrompt() {
  const categorieen = abCategorieLabels().join(', ');
  const leeftijden = abLeeftijdLabels().join(', ');
  const hek = '```';

  return [
    '---',
    'name: bankscript',
    'description: >',
    '  Gebruik deze skill wanneer Joris een ruwe activiteit-omschrijving (losse notities, een idee, geplakte tekst van',
    '  activiteitenbank.nl, of uitgewerkte tekst) wil omzetten naar kant-en-klare tekst voor het "Nieuwe activiteit"-formulier',
    '  in de admin panel van de Activiteitenbank (onderdeel van de Vlietkinderen website). Triggers: "activiteit toevoegen',
    '  aan de activiteitenbank", "zet dit om voor de activiteitenbank", "nieuwe activiteit invullen", "activiteitenbank',
    '  formulier", "maak hier een activiteit van", "activiteit voor de bank uitwerken", "zet in het format/template",',
    '  "bankscript" of varianten daarop, of het plakken van een activiteit gekopieerd van activiteitenbank.nl. De skill',
    '  levert ALTIJD alle acht vaste labels (Titel, Inleiding, Kern, Slot, Aangeleverd door, Voorgestelde emoji,',
    '  Voorgestelde categorie, Voorgestelde leeftijd) in platte tekst, in een codeblok zodat de sterretjes letterlijk',
    '  gekopieerd kunnen worden. Als de aangeleverde tekst te dun is, stelt de skill eerst 2-3 gerichte vragen voor ze de',
    '  velden invult.',
    '---',
    '',
    '# Bankscript – Vlietkinderen Activiteitenbank',
    '',
    '## Doel',
    'Zet een ruwe activiteit-omschrijving van Joris om in kant-en-klare tekst die hij direct kan kopiëren naar de velden van het "Nieuwe activiteit"-formulier in de admin panel van de Activiteitenbank. Schrijf in het Nederlands, in de je-vorm, gericht op de pedagogisch medewerker die de activiteit gaat uitvoeren. Praktisch en vriendelijk, consistent met bestaande AGLV-activiteiten.',
    '',
    'Geef ALLEEN het output-blok terug (zie Stap 4) wanneer de aangeleverde tekst al genoeg bevat — geen aparte inleiding of uitleg ervoor of erna, tenzij Joris daar expliciet om vraagt.',
    '',
    '---',
    '',
    '## Stap 1 – Beoordeel de aangeleverde tekst',
    '',
    'Kijk of de aangeleverde tekst genoeg bevat om Titel, Inleiding, Kern en Slot goed te kunnen invullen (een duidelijk idee/thema, wat de kinderen gaan doen, en idealiter leeftijdsgroep, materialen en tijd). Geplakte activiteiten van activiteitenbank.nl bevatten meestal genoeg — ontbreekt bijvoorbeeld het Slot in de brontekst, verzin dan zelf een passende afsluiting en meld dat kort na het blok.',
    '',
    '- **Genoeg informatie?** Ga direct door naar Stap 2.',
    '- **Te dun?** Stel eerst 2-3 gerichte vragen, één voor één zoals de kindobservatie-skill dat doet, bijvoorbeeld:',
    '  - Wat is het doel of thema van de activiteit?',
    '  - Voor welke leeftijdsgroep is dit bedoeld?',
    '  - Hoeveel tijd en welke materialen zijn nodig?',
    '',
    '  Wacht op de antwoorden voor je de velden invult.',
    '',
    '---',
    '',
    '## Stap 2 – Vul de vrije-tekstvelden',
    '',
    'Schrijf de volgende vijf velden in platte tekst:',
    '',
    '1. **Titel** — kort en pakkend, maximaal ~5 woorden, zonder emoji.',
    '2. **Inleiding** — hoe je de activiteit bij de kinderen introduceert.',
    '3. **Kern** — hoe de activiteit verloopt, stap voor stap. Verwerk hierin ook eventuele benodigdheden en duur uit de brontekst (er is geen apart veld voor), in lopende tekst.',
    '4. **Slot** — hoe je afsluit.',
    '5. **Aangeleverd door** — de voornaam van de bedenker uit de brontekst (bijv. uit "Gemaakt door X van KC Y"); standaard "Joris" als niemand anders wordt genoemd.',
    '',
    'Belangrijke regels voor deze teksten:',
    '- **Geen markdown-opmaak** binnen de lopende tekst: geen sterretjes, hekjes, of streepjes als lijst-bullets. De editor van de admin panel ondersteunt geen markdown-syntax.',
    '- Gebruik nergens het patroon `**woord:**` in de lopende tekst zelf — dat wordt gelezen als een nieuw label en knipt de tekst doormidden.',
    '- Inleiding, Kern en Slot mogen over meerdere regels/alinea\'s lopen.',
    '- Geen enkel veld mag leeg blijven.',
    '',
    '---',
    '',
    '## Stap 3 – Geef suggesties voor de selectievelden',
    '',
    'Deze drie velden zijn **geen vrije tekst** maar knoppen in de admin panel. Genereer hiervoor geen lopende tekst, maar benoem de suggestie zodat Joris weet wat hij moet aanklikken.',
    '',
    '6. **Voorgestelde emoji** — kies precies één emoji die inhoudelijk het beste bij de activiteit past. Elke emoji mag gebruikt worden, ook buiten een vaste lijst — kies wat het meest logisch is (bijv. 🪓 voor houtsnijden, 🧬 voor een evolutiespel, 🍣 voor sushi maken, 🏒 voor dweilhockey). Neem de emoji over uit de brontekst (de titel-emoji van activiteitenbank.nl) als die goed past.',
    '7. **Voorgestelde categorie** (één of meer, gescheiden door komma\'s) — uitsluitend uit: ' + categorieen + '.',
    '8. **Voorgestelde leeftijd** (één of meer, gescheiden door komma\'s) — uitsluitend uit: ' + leeftijden + '.',
    '',
    'Twijfel je over categorie of leeftijd, kies dan de dichtstbijzijnde waarde uit de lijst. Verzin nooit een nieuwe waarde. Als de brontekst een categorie/leeftijd noemt die niet in de lijst staat (bijv. "Spel" of "2-4 jaar"), kies de dichtstbijzijnde toegestane waarde en meld dat kort na het blok.',
    '',
    '---',
    '',
    '## Stap 4 – Output-format',
    '',
    'Lever het resultaat altijd in deze vaste structuur, **in een codeblok** (drie backticks eromheen), zodat de sterretjes letterlijk blijven staan bij het kopiëren in plaats van gerenderd te worden als vetgedrukte tekst:',
    '',
    hek,
    '**Titel:** ...',
    '',
    '**Inleiding:** ...',
    '',
    '**Kern:** ...',
    '',
    '**Slot:** ...',
    '',
    '**Aangeleverd door:** ...',
    '',
    '**Voorgestelde emoji:** ...',
    '',
    '**Voorgestelde categorie:** ...',
    '',
    '**Voorgestelde leeftijd:** ...',
    hek,
    '',
    'Alle acht labels moeten aanwezig zijn, exact zo geschreven, inclusief de sterretjes en de dubbele punt.',
    '',
    '---',
    '',
    '## Toon en schrijfstijl',
    '',
    '- Praktische, vriendelijke toon in de je-vorm, gericht op de pedagogisch medewerker die de activiteit uitvoert.',
    '- Consistent met bestaande AGLV-activiteiten: concreet, uitvoerbaar, geen vaag taalgebruik.',
    '- Platte tekst binnen Inleiding, Kern en Slot — geen markdown-opmaak.',
    '- Houd Titel kort en pakkend (max ~5 woorden, zonder emoji).'
  ].join('\n');
}
